[toolchain]
profile = "minimal"
channel = "nightly-2024-12-25"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
targets = [
    "aarch64-unknown-none",
    "aarch64-unknown-none-softfloat",
]
